# Generated by Django 3.2.8 on 2021-10-25 18:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('event_date',),
            },
        ),
        migrations.CreateModel(
            name='LatestNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('newsletter', models.TextField()),
                ('news_img', models.ImageField(upload_to='news_images')),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('upload_date',),
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ccu_gallery')),
                ('image_name', models.CharField(max_length=150)),
                ('date_added', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('student_img', models.ImageField(upload_to='student_images')),
                ('body', models.TextField(max_length=400)),
                ('department', models.CharField(max_length=250)),
            ],
        ),
    ]
