# Generated by Django 3.2.8 on 2021-10-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_ccualumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='body',
            field=models.TextField(max_length=250),
        ),
    ]
