# Generated by Django 3.2.8 on 2021-10-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_testimony_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-event_date',)},
        ),
        migrations.AlterModelOptions(
            name='latestnew',
            options={'ordering': ('-upload_date',)},
        ),
    ]
