# Generated by Django 3.2.8 on 2021-11-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211028_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=250)),
                ('member_img', models.ImageField(upload_to='member_images')),
                ('member_position', models.CharField(max_length=200)),
                ('twitter_url', models.CharField(max_length=200)),
                ('facebook_url', models.CharField(max_length=250)),
                ('instagram_url', models.CharField(max_length=200)),
            ],
        ),
    ]
