# Generated by Django 3.2.8 on 2021-11-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=250)),
                ('member_img', models.ImageField(upload_to='member_images')),
                ('member_position', models.CharField(max_length=200)),
                ('twitter_url', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
