# Generated by Django 3.2.8 on 2021-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20211111_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Venue',
            field=models.CharField(default='', max_length=250),
        ),
    ]
