# Generated by Django 3.2.8 on 2021-11-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Venue',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
