# Generated by Django 4.0.1 on 2022-01-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_event_news_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='news_img',
            new_name='event_img',
        ),
    ]
