# Generated by Django 4.0.1 on 2022-02-15 09:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_news_img_event_event_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
