# Generated by Django 4.0.1 on 2022-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_memberbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbenefit',
            name='title',
            field=models.CharField(default='Alumni Benefit', max_length=250),
        ),
    ]
