# Generated by Django 4.0.1 on 2022-02-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_memberbenefit_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberBenefit',
        ),
    ]
